import Link from "next/link";
import { company } from "@/data/company";

export const metadata={title:"About"};
const principles=[
 ["01","Heritage","Keep historical context separate from the current legal entity until the corporate timeline is approved."],
 ["02","Evidence","Describe projects, roles and capabilities at the level that available documentation supports."],
 ["03","Execution","Make engineering, site coordination and construction discipline part of the company story."],
 ["04","Growth","Use a structured publishing system so new projects and approved corporate information can be added cleanly."],
];
export default function AboutPage(){return <main className="v12-shell v12-page"><section className="v12-page-hero"><div className="v12-container v12-page-hero__grid"><div><span className="v12-kicker">About Miror / 01</span></div><div><h1 className="v12-display">A construction story with a clear line between heritage, evidence and the company that exists today.</h1><p>Miror Constructions and Consultancy Private Limited is the current legal entity. The construction business predates the 2019 entity according to supplied company context, so the website keeps those timelines distinct.</p></div></div></section><section className="v12-section" id="company-record"><div className="v12-container"><div className="v12-section__head"><div><span className="v12-kicker">Corporate record</span></div><div className="v12-section__head-copy"><h2>The current company, clearly identified.</h2></div></div><div className="v12-data-grid">{[["Legal name",company.legalName],["CIN",company.cin],["Incorporated",new Date(company.incorporationDate).toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"})],["Status",company.status],["Registered office",company.registeredOffice],["Publication rule","Unsupported claims require approval before publication."]].map(([label,value],i)=><article className="v12-data-card" key={label}><span className="v12-data-card__number">{String(i+1).padStart(2,"0")}</span><h3>{label}</h3><p>{value}</p></article>)}</div></div></section><section className="v12-section v12-section--dark" id="legacy"><div className="v12-container"><div className="v12-section__head"><div><span className="v12-kicker v12-kicker-light">Legacy / 02</span></div><div className="v12-section__head-copy"><h2>Build the timeline from approved milestones, not assumptions.</h2><p>The site is prepared for a fuller history: business origins, project phases, expansion and the formation of the 2019 private limited entity can be inserted once the company provides the final chronology.</p><Link className="v12-button v12-button--light" href="/contact">Update the company story ↗</Link></div></div><div className="v12-dark-grid">{principles.map(([n,t,b])=><article className="v12-dark-card" key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></div></section></main>}
